2022-12-15 04:59:23 I Pelic Print           "Connet 20625 successfully!!!"
2022-12-15 04:59:23 I Pelic Get_alltests    "Get project name:Pelican id:20625 all testplans"
2022-12-15 04:59:26 I Pelic Get_alltests    "{10332183: {'id': 10332183, 'name': 'HW Test Plan', 'archived': False, 'index': '10332183:HW Test Plan'}, 10329003: {'id': 10329003, 'name': 'Packaging Verification Plan', 'archived': False, 'index': '10329003:Packaging Verification Plan'}, 10183809: {'id': 10183809, 'name': 'Product Verification Test Plan', 'archived': False, 'index': '10183809:Product Verification Test Plan'}, 10219787: {'id': 10219787, 'name': 'Tonly SW Test Plan', 'archived': False, 'index': '10219787:Tonly SW Test Plan'}}"
2022-12-15 04:59:26 I Pelic Get_alltests    "Get project name:Pelican id:20625 all testplans successful!!!"
2022-12-15 05:16:02 E Pelic Print           "('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None))"
2022-12-15 05:16:19 E Pelic Print           "('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None))"
2022-12-15 05:16:19 E Pelic Print           "('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None))"
2022-12-15 05:19:44 I Pelic tidy_alltestcas "53"
2022-12-15 05:22:01 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10326101/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x03017910>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))"
2022-12-15 05:22:01 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10326101/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AAF86D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:01 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10326101/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AAF85D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:01 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10326101/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AAF8490>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:01 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10326101/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AAF84D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:01 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10326101/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AAF8690>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:01 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10326101/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AAF84B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:01 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10326101/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AAF8670>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:01 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10326101/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AAF8630>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:01 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10326101/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AAF8530>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:01 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04A6E070>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))"
2022-12-15 05:22:01 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114923/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x020D6070>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))"
2022-12-15 05:22:01 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114928/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04A6E650>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))"
2022-12-15 05:22:01 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114944/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09966E10>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))"
2022-12-15 05:22:01 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114937/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09966930>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))"
2022-12-15 05:22:01 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114945/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AAF8330>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))"
2022-12-15 05:22:01 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114937/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AAF82D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:01 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114923/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099665B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:01 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114935/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951CD0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))"
2022-12-15 05:22:01 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114928/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09966530>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:01 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114944/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09966730>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:01 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10326101/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x020D6130>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:08 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x020D6730>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:08 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x03025C10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:08 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x020D6EB0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))"
2022-12-15 05:22:08 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114926/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x03025A70>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))"
2022-12-15 05:22:08 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114933/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951110>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))"
2022-12-15 05:22:08 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114931/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09941530>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))"
2022-12-15 05:22:08 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114920/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x03017DB0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))"
2022-12-15 05:22:08 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114925/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x03025490>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))"
2022-12-15 05:22:08 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099662B0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))"
2022-12-15 05:22:08 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114930/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x030172D0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))"
2022-12-15 05:22:08 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114921/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0208EF10>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))"
2022-12-15 05:22:08 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114932/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09941B10>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))"
2022-12-15 05:22:08 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114924/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x020D68F0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))"
2022-12-15 05:22:08 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114929/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04A6EBD0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))"
2022-12-15 05:22:08 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114934/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099516F0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))"
2022-12-15 05:22:09 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114945/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x020D68B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:09 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114945/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099417D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:09 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114945/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09941650>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:09 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114945/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09941790>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:09 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114945/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099417B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:09 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114945/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09941830>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:09 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x03025C50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:09 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114935/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x020D6DF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:09 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114935/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04A6E7F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:09 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114935/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04A6E950>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:09 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114935/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04A6E930>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:09 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114935/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04A6E8B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:09 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114935/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04A6E7F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:09 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114935/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04A6E950>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:09 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114935/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04A6E930>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:09 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114935/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04A6E8B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:09 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114935/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04A6E7F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:09 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114935/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04A6E950>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:09 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114935/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04A6E930>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:09 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114935/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04A6E8B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:09 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114935/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04A6E7F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:09 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114935/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04A6E950>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:09 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114935/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04A6E930>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:09 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114935/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04A6E8B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:09 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114935/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04A6E7F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:09 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114935/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04A6E950>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:09 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09941710>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:09 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099417F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:09 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09941790>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:09 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09941730>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:09 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09941650>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:09 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09941710>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:09 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099417F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:09 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09941790>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:09 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09941730>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:09 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09941650>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:09 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09941710>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:09 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099417F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:09 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09941790>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:09 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09941730>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:09 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09941650>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:09 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09941710>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:09 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099417F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:09 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09941790>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:09 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09941730>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:09 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09941650>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:09 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09941710>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:09 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099417F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:09 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09941790>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:09 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09941730>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:09 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09941650>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:09 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09941710>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:09 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099417F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:09 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09941790>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:09 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09941730>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:09 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09941650>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:09 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114937/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x020D60B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:09 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114937/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x03017F30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114937/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x03017E70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114937/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x030175F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114937/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x03017F30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114937/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x03017E70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09941710>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10326101/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x020D6450>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10326101/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099513D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10326101/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951B90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10326101/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099513F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10326101/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951CB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10326101/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951BB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04A6EDF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AAF8530>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AAF8050>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AAF8970>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AAF8170>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AAF86F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AAF8610>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AAF8790>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AAF8210>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AAF8890>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AAF85F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AAF8750>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AAF8530>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AAF8050>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AAF8970>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AAF8170>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AAF86F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AAF8610>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AAF8790>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AAF8210>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AAF8890>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AAF85F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AAF8750>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AAF8530>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AAF8050>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AAF8970>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AAF8170>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AAF86F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AAF8610>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AAF8790>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AAF8210>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AAF8890>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AAF85F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AAF8750>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AAF8530>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AAF8050>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AAF8970>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AAF8170>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AAF86F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AAF8610>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AAF8790>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AAF8210>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AAF8890>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AAF85F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AAF8750>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AAF8530>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AAF8050>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AAF8970>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04A6E330>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951550>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099512F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099512D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099514F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951550>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099512F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099512D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099514F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951550>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099512F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099512D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099514F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951550>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099512F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099512D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099514F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951550>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099512F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099512D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099514F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951550>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099512F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099512D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099514F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951550>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099512F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099512D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099514F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951550>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099512F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099512D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099514F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951550>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099512F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099512D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099514F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951550>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099512F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099512D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099514F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951550>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099512F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099512D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099514F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951550>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099512F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099512D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099514F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951550>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099512F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099512D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099514F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951550>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099512F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099512D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099514F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951550>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099512F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099512D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099514F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951550>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099512F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099512D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:10 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099514F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:18 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951550>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:18 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099512F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:18 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099512D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:18 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099514F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:18 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951550>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:18 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099512F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:18 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099512D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:18 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099514F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:18 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951550>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:18 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099512F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:18 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099512D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:18 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099514F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:18 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951550>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:18 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099512F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:18 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099512D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:18 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099514F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:18 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09941C90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:18 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951FB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:18 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951710>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:18 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951ED0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:18 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951F90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:18 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951430>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:18 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951DD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:18 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951FB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:18 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951710>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:18 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951ED0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:18 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951F90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:18 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951430>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:18 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951DD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:18 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951FB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:18 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951710>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:18 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951ED0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951F90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951430>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951DD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951FB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951710>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951ED0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951F90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951430>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951DD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951FB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951710>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951ED0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951F90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951430>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951DD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951FB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951710>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951ED0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951F90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951430>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951DD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951FB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951710>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951ED0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951F90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951430>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951DD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951FB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951710>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951ED0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951F90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951430>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951DD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951FB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951710>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951ED0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951F90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951430>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951DD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951FB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951710>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951ED0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951DD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951430>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951EF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951710>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099516F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951ED0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951DD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951430>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951EF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951710>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099516F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951ED0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951DD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951430>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951EF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951710>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099516F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951ED0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951690>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951550>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114930/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x030255D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114921/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0208E8D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114932/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951910>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114924/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AB09570>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114929/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09941110>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114934/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0208E450>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114926/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0300D590>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114933/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x030178D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114931/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AB09030>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114920/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x03017650>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114925/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09941330>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099512F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09966BF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09966F30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114930/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09966E70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114921/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099666F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114932/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09966A90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114924/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099661B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114929/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x020D6930>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114934/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x03017C10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:20 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114926/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x020D6110>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:20 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114933/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x020D6330>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:20 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114931/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09941070>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:20 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114920/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09951F70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:20 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114925/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09941650>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:20 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114936/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099512D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:20 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114927/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09966550>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:20 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114922/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09966DB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:20 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114930/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09966590>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:20 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114921/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09966EF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:20 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114932/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x020D6A70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:20 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114924/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099660B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:20 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114929/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x020D6E90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:20 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114934/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x020D6470>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:20 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114926/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x020D6FF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:20 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114933/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x020D6DF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:20 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114931/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099411B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:20 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114920/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x099512B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:20 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114925/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09941D70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:22:19 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10114923/upstreamrelationships (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x03025D10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:23:42 E Pelic Print           "('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None))"
2022-12-15 05:23:42 E Pelic Print           "('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None))"
2022-12-15 05:23:44 E Pelic Print           "('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None))"
2022-12-15 05:23:46 E Pelic Print           "('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None))"
2022-12-15 05:24:47 I Pelic Print           "DROP TABLE IF EXISTS testcases:successful"
2022-12-15 05:24:47 I Pelic Print           "CREATE TABLE IF NOT EXISTS testcases (                             testplan_id INT,                             testplan_name TEXT,                             testgroup_id INT,                             testgroup_name TEXT,                             testcycle_id INT,                             testcycle_name TEXT,                             rel TEXT,                             id INT,                             uniqueid TEXT,                             name TEXT,                             status TEXT,                             upstream TEXT,                             downstream TEXT,                             executionDate TEXT) ENGINE=InnoDB DEFAULT CHARSET=utf8:successful"
2022-12-15 05:24:48 I Pelic update_database "Insert testcases table successful"
2022-12-15 05:24:48 I Pelic Print           "CREATE TABLE IF NOT EXISTS tests (                             testplan_id INT,                             testplan_name TEXT,                             testplan_status TEXT,                             rel TEXT, status TEXT,                             count INT, date TEXT) ENGINE=InnoDB DEFAULT CHARSET=utf8:successful"
2022-12-15 05:24:48 I Pelic Print           "DELETE FROM tests WHERE date='2022-12-15':successful"
2022-12-15 05:24:48 I Pelic Print           "SELECT testplan_id FROM tests GROUP BY testplan_id:successful"
2022-12-15 05:24:48 I Pelic Print           "SELECT testplan_name FROM tests WHERE testplan_id=10332183 LIMIT 1:successful"
2022-12-15 05:24:48 I Pelic Print           "UPDATE tests SET testplan_status='Active' WHERE testplan_id=10332183:successful"
2022-12-15 05:24:48 I Pelic Print           "SELECT testplan_name FROM tests WHERE testplan_id=10329003 LIMIT 1:successful"
2022-12-15 05:24:48 I Pelic Print           "UPDATE tests SET testplan_status='Active' WHERE testplan_id=10329003:successful"
2022-12-15 05:24:48 I Pelic Print           "SELECT testplan_name FROM tests WHERE testplan_id=10183809 LIMIT 1:successful"
2022-12-15 05:24:48 I Pelic Print           "UPDATE tests SET testplan_status='Active' WHERE testplan_id=10183809:successful"
2022-12-15 05:24:48 I Pelic Print           "INSERT INTO tests (testplan_id, testplan_name, testplan_status, rel, status, count, date) SELECT testplan_id, testplan_name, 'Active' as testplan_status, rel, status, count((@rn := @rn + 1)) as count, '2022-12-15' as date FROM testcases cross join (select @rn := 0) const GROUP BY testplan_id, rel, status:successful"
2022-12-15 05:24:48 I Pelic update_database "Insert tests table successful"
2022-12-15 05:24:48 I Pelic Print           "CREATE TABLE IF NOT EXISTS testapproval (                                 rel TEXT, team TEXT, status TEXT, upstream TEXT, count INT, date TEXT                                 ) ENGINE=InnoDB DEFAULT CHARSET=utf8:successful"
2022-12-15 05:24:48 I Pelic Print           "DROP TABLE IF EXISTS alltestapproval:successful"
2022-12-15 05:24:48 I Pelic Print           "CREATE TABLE IF NOT EXISTS alltestapproval (                                 id INT, uniqueid TEXT, name TEXT, status TEXT, rel TEXT, team TEXT, upstream TEXT                                 ) ENGINE=InnoDB DEFAULT CHARSET=utf8:successful"
2022-12-15 05:24:48 I Pelic Print           "DELETE FROM testapproval WHERE date='2022-12-15':successful"
2022-12-15 05:24:48 I Pelic Print           "INSERT INTO testapproval (rel, team, status, count, date, upstream) SELECT rel, team, status, count((@rn := @rn + 1)) as count, '2022-12-15' as date, upstream FROM alltestapproval cross join (select @rn := 0) const GROUP BY rel, team, status, upstream:successful"
2022-12-15 05:25:48 I Pelic Get_allfeatuers "[{'id': 10281768, 'name': 'Legal docs (App only)', 'documentKey': 'pel-FEAT-755', 'statusId': 156584, 'status': 'Proposal'}, {'id': 9783814, 'name': 'Google Bisto Voice Assistance Certification - Audio (Draft)', 'documentKey': 'pel-FEAT-182', 'statusId': 156761, 'status': 'Previously approved'}, {'id': 9783818, 'name': 'Tx Rogue One Plus (2 microphones)', 'documentKey': 'pel-FEAT-156', 'statusId': 156584, 'status': 'Proposal'}, {'id': 9783819, 'name': 'Tx Glider (Wind NR for 2 mics and optional extra input)', 'documentKey': 'pel-FEAT-162', 'statusId': 156584, 'status': 'Proposal'}, {'id': 9783828, 'name': 'Rx In-Ear semi-open ANC with best performance tier', 'documentKey': 'pel-FEAT-189', 'statusId': 156761, 'status': 'Previously approved'}, {'id': 9783850, 'name': 'Auto-Listen-In/Own voice detection (Always on VPU) [REJECTED]', 'documentKey': 'pel-FEAT-149', 'statusId': 156412, 'status': 'Rejected'}, {'id': 9783858, 'name': 'VPU Sensitivity Calibration [REJECTED]', 'documentKey': 'pel-FEAT-39', 'statusId': 156412, 'status': 'Rejected'}, {'id': 9783863, 'name': 'Wind Detection for Adaptive FF ANC Control', 'documentKey': 'pel-FEAT-166', 'statusId': 156880, 'status': 'Pending platform (only in project)'}, {'id': 9783865, 'name': 'Google Bisto - Push To Talk (PTT)', 'documentKey': 'pel-FEAT-183', 'statusId': 156409, 'status': 'Draft'}, {'id': 9783866, 'name': 'Google Bisto - Always on Voice (AoV)', 'documentKey': 'pel-FEAT-184', 'statusId': 156409, 'status': 'Draft'}, {'id': 9783870, 'name': 'ID Concept and Wearingstyle', 'documentKey': 'pel-FEAT-43', 'statusId': 156409, 'status': 'Draft'}, {'id': 10142763, 'name': 'Spotify Tap', 'documentKey': 'pel-FEAT-622', 'statusId': 156761, 'status': 'Previously approved'}, {'id': 9783880, 'name': 'Wireless Charging Pad [FCS]', 'documentKey': 'pel-FEAT-152', 'statusId': 156584, 'status': 'Proposal'}, {'id': 10170531, 'name': 'USB cable', 'documentKey': 'pel-FEAT-750', 'statusId': 156584, 'status': 'Proposal'}, {'id': 9783882, 'name': 'Battery performance', 'documentKey': 'pel-FEAT-50', 'statusId': 156584, 'status': 'Proposal'}, {'id': 9783883, 'name': 'Charging', 'documentKey': 'pel-FEAT-51', 'statusId': 156761, 'status': 'Previously approved'}, {'id': 10096106, 'name': 'Speaker driver size', 'documentKey': 'pel-FEAT-616', 'statusId': 156584, 'status': 'Proposal'}, {'id': 9783892, 'name': 'Device Tracking', 'documentKey': 'pel-FEAT-59', 'statusId': 156761, 'status': 'Previously approved'}, {'id': 9783894, 'name': 'Item tracking', 'documentKey': 'pel-FEAT-61', 'statusId': 156761, 'status': 'Previously approved'}, {'id': 9783895, 'name': 'Jabra production support', 'documentKey': 'pel-FEAT-62', 'statusId': 156761, 'status': 'Previously approved'}, {'id': 10099257, 'name': 'Support for Multiple Voice Assistants, wake word', 'documentKey': 'pel-FEAT-617', 'statusId': 156409, 'status': 'Draft'}, {'id': 9783905, 'name': 'Customize Bluetooth name', 'documentKey': 'pel-FEAT-72', 'statusId': 156409, 'status': 'Draft'}, {'id': 9783837, 'name': 'Rx MySound Music', 'documentKey': 'pel-FEAT-29', 'statusId': 156412, 'status': 'Rejected'}, {'id': 9783838, 'name': 'Rx MySound Calls', 'documentKey': 'pel-FEAT-28', 'statusId': 156412, 'status': 'Rejected'}, {'id': 9783839, 'name': 'Rx Audio Sealing test In-Ear', 'documentKey': 'pel-FEAT-27', 'statusId': 156412, 'status': 'Rejected'}, {'id': 9783793, 'name': 'Find my head phones (App only)', 'documentKey': 'pel-FEAT-2', 'statusId': 156410, 'status': 'Approved'}, {'id': 10072160, 'name': 'ANC control (App only)', 'documentKey': 'pel-FEAT-614', 'statusId': 156410, 'status': 'Approved'}, {'id': 10281711, 'name': 'Link to device FAQ (App only)', 'documentKey': 'pel-FEAT-752', 'statusId': 156410, 'status': 'Approved'}, {'id': 10281726, 'name': 'Link to "Buy Jabra" (App only)', 'documentKey': 'pel-FEAT-753', 'statusId': 156410, 'status': 'Approved'}, {'id': 10281733, 'name': 'Soundscapes (App only)', 'documentKey': 'pel-FEAT-754', 'statusId': 156410, 'status': 'Approved'}, {'id': 10285256, 'name': 'Technical info (summary)', 'documentKey': 'pel-FEAT-756', 'statusId': 156410, 'status': 'Approved'}, {'id': 10313492, 'name': 'Virtual Surround Sound control', 'documentKey': 'pel-FEAT-890', 'statusId': 156409, 'status': 'Draft'}, {'id': 9783803, 'name': 'User Audio Configuration', 'documentKey': 'pel-FEAT-11', 'statusId': 156410, 'status': 'Approved'}, {'id': 9783812, 'name': 'Sidetone', 'documentKey': 'pel-FEAT-161', 'statusId': 156410, 'status': 'Approved'}, {'id': 9783831, 'name': 'Rx Music User Equalizer', 'documentKey': 'pel-FEAT-24', 'statusId': 156410, 'status': 'Approved'}, {'id': 9783834, 'name': 'Rx Communication User Equalizer', 'documentKey': 'pel-FEAT-23', 'statusId': 156410, 'status': 'Approved'}, {'id': 10234733, 'name': 'Rx Virtual Surround Sound "Dolby Spatial Audio"', 'documentKey': 'pel-FEAT-751', 'statusId': 156410, 'status': 'Approved'}, {'id': 9783852, 'name': 'Sidetone', 'documentKey': 'pel-FEAT-34', 'statusId': 156410, 'status': 'Approved'}, {'id': 9783853, 'name': 'Sidetone - Low Latency Noise Reduction', 'documentKey': 'pel-FEAT-35', 'statusId': 156410, 'status': 'Approved'}, {'id': 9783878, 'name': 'Quick Start Guide and Manuals', 'documentKey': 'pel-FEAT-48', 'statusId': 156410, 'status': 'Approved'}, {'id': 9783879, 'name': 'SKUs', 'documentKey': 'pel-FEAT-49', 'statusId': 156410, 'status': 'Approved'}, {'id': 9783896, 'name': 'SKU awareness [TBD]', 'documentKey': 'pel-FEAT-64', 'statusId': 156410, 'status': 'Approved'}, {'id': 9783907, 'name': 'Firmware update OTA', 'documentKey': 'pel-FEAT-74', 'statusId': 156410, 'status': 'Approved'}, {'id': 9783904, 'name': 'Change headset language pack', 'documentKey': 'pel-FEAT-71', 'statusId': 156410, 'status': 'Approved'}, {'id': 9783906, 'name': 'Device configuration changes synced to applications', 'documentKey': 'pel-FEAT-73', 'statusId': 156410, 'status': 'Approved'}, {'id': 9783919, 'name': 'Symmetric and Seamless Design for TWS', 'documentKey': 'pel-FEAT-84', 'statusId': 156410, 'status': 'Approved'}, {'id': 9783920, 'name': 'Voice guidance', 'documentKey': 'pel-FEAT-85', 'statusId': 156410, 'status': 'Approved'}, {'id': 10091928, 'name': 'Sound Modes', 'documentKey': 'pel-FEAT-615', 'statusId': 156410, 'status': 'Approved'}, {'id': 9783928, 'name': 'In- and out of ear detection', 'documentKey': 'pel-FEAT-151', 'statusId': 156410, 'status': 'Approved'}, {'id': 9783931, 'name': 'Mute reminder tones On / Off', 'documentKey': 'pel-FEAT-94', 'statusId': 156410, 'status': 'Approved'}, {'id': 9783935, 'name': 'UI Configurable Buttons // MyControls', 'documentKey': 'pel-FEAT-99', 'statusId': 156410, 'status': 'Approved'}, {'id': 10311551, 'name': 'Auto hear through mode in mono use', 'documentKey': 'pel-FEAT-889', 'statusId': 156409, 'status': 'Draft'}, {'id': 10292215, 'name': 'Wireless Charging Pad [VP1]', 'documentKey': 'pel-FEAT-786', 'statusId': 156409, 'status': 'Draft'}, {'id': 10294178, 'name': 'Wireless Charging Pad [VP1]', 'documentKey': 'pel-FEAT-888', 'statusId': 156409, 'status': 'Draft'}]"
2022-12-15 05:25:48 I Pelic Print           "CREATE TABLE IF NOT EXISTS features (                                rel TEXT, status TEXT, count INT, date TEXT) ENGINE=InnoDB DEFAULT CHARSET=utf8:successful"
2022-12-15 05:25:48 I Pelic Print           "CREATE TABLE IF NOT EXISTS allfeatures (                                id INT, uniqueid TEXT, name TEXT, status TEXT, rel TEXT,test_status TEXT) ENGINE=InnoDB DEFAULT CHARSET=utf8:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM features WHERE date='2022-12-15':successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=20944440:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=20494242:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=20485782:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=20485558:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=20477465:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=20477231:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=20476941:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=20424968:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=20411798:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=20330590:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=20330589:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=20232016:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=10281768:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=9783814:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=9783818:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=9783819:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=9783828:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=9783850:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=9783858:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=9783863:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=9783865:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=9783866:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=9783870:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=10142763:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=9783880:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=10170531:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=9783882:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=9783883:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=10096106:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=9783892:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=9783894:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=9783895:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=10099257:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=9783905:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=9783837:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=9783838:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=9783839:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=9783793:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=10072160:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=10281711:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=10281726:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=10281733:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=10285256:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=10313492:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=9783803:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=9783812:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=9783831:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=9783834:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=10234733:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=9783852:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=9783853:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=9783878:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=9783879:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=9783896:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=9783907:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=9783904:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=9783906:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=9783919:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=9783920:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=10091928:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=9783928:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=9783931:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=9783935:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=10311551:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=10292215:successful"
2022-12-15 05:25:48 I Pelic Print           "DELETE FROM allfeatures WHERE id=10294178:successful"
2022-12-15 05:25:48 I Pelic Print           "INSERT INTO features (rel, status, count, date)                                 SELECT rel, status, count((@rn := @rn + 1)) as count, '2022-12-15' as date FROM allfeatures cross join (select @rn := 0) const GROUP BY rel, status:successful"
2022-12-15 05:25:57 I Pelic Get_allchangere "[]"
2022-12-15 05:25:57 I Pelic Print           "CREATE TABLE IF NOT EXISTS changes (                                 rel TEXT, status TEXT, priority TEXT,                                 requester TEXT, date TEXT, count INT) ENGINE=InnoDB DEFAULT CHARSET=utf8:successful"
2022-12-15 05:25:57 I Pelic Print           "CREATE TABLE IF NOT EXISTS allchanges (                                 id INT, uniqueid TEXT, name TEXT,                                 status TEXT, rel TEXT, priority TEXT,                                 requester TEXT) ENGINE=InnoDB DEFAULT CHARSET=utf8:successful"
2022-12-15 05:25:57 I Pelic Print           "DELETE FROM changes WHERE date='2022-12-15':successful"
2022-12-15 05:25:57 I Pelic Print           "INSERT INTO changes (                                 rel, status, priority, requester, date, count)                                 SELECT rel, status, priority, requester, '2022-12-15' as date, count((@rn := @rn + 1)) as count FROM allchanges                                 cross join (select @rn := 0) const GROUP BY rel, status, priority, requester:successful"
2022-12-15 05:27:01 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10342322/parent (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0208ECD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:27:01 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10342322/parent (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0208E290>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:27:01 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10342322/parent (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0208E650>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:27:01 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10342322/parent (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0208EC10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:27:01 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10342322/parent (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0208EBF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:27:02 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10342322/parent (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0208EA50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:27:05 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10342322/parent (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0208EBD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:27:06 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10342322/parent (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0208ED30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:27:06 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10342322/parent (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0208E870>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:27:12 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10342322/parent (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0208E8F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:27:12 E Pelic Print           "HTTPSConnectionPool(host='jabra.jamacloud.com', port=443): Max retries exceeded with url: /rest/v1/items/10342322/parent (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0208E530>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
2022-12-15 05:27:33 I Pelic Print           "CREATE TABLE IF NOT EXISTS designspec (                            rel TEXT, team TEXT, status TEXT, count INT, date text) ENGINE=InnoDB DEFAULT CHARSET=utf8:successful"
2022-12-15 05:27:33 I Pelic Print           "CREATE TABLE IF NOT EXISTS alldesignspec (                             id INT, uniqueid TEXT, name TEXT, status TEXT, rel TEXT, team TEXT) ENGINE=InnoDB DEFAULT CHARSET=utf8:successful"
2022-12-15 05:27:33 I Pelic Print           "DELETE FROM designspec WHERE date='2022-12-15':successful"
2022-12-15 05:27:33 I Pelic Print           "DELETE FROM alldesignspec WHERE id=9785024:successful"
2022-12-15 05:27:33 I Pelic Print           "DELETE FROM alldesignspec WHERE id=9785019:successful"
2022-12-15 05:27:33 I Pelic Print           "INSERT INTO designspec (rel, team, status, count, date) SELECT rel, team, status, count((@rn := @rn + 1)) as count, '2022-12-15' as date FROM alldesignspec cross join (select @rn := 0) const GROUP BY rel, team, status:successful"
2022-12-15 05:27:41 I Pelic Get_alluserstor "[]"
2022-12-15 05:27:41 I Pelic Print           "CREATE TABLE IF NOT EXISTS userstories (                 rel TEXT, status TEXT, count INT, date TEXT) ENGINE=InnoDB DEFAULT CHARSET=utf8:successful"
2022-12-15 05:27:41 I Pelic Print           "CREATE TABLE IF NOT EXISTS alluserstories (                 id INT, uniqueid TEXT, name TEXT, status TEXT, rel TEXT) ENGINE=InnoDB DEFAULT CHARSET=utf8:successful"
2022-12-15 05:27:41 I Pelic Print           "DELETE FROM userstories WHERE date='2022-12-15':successful"
2022-12-15 05:27:41 I Pelic Print           "INSERT INTO userstories (rel, status, count, date) SELECT rel, status, count((@rn := @rn + 1)) as count, '2022-12-15' as date FROM alluserstories cross join (select @rn := 0) const GROUP BY rel, status:successful"
Traceback (most recent call last):
  File "E:\New Jira_Jama\Jama_jira_script\REST_Jama20201207.py", line 196, in fetch_data
    jamadata.Get_and_Save()
  File "E:\New Jira_Jama\Jama_jira_script\Subprogress.py", line 461, in Get_and_Save
    self.Get_alldefects()
  File "E:\New Jira_Jama\Jama_jira_script\Subprogress.py", line 606, in Get_alldefects
    self.P_changedefects =  self.get_change_defects(projectId, defects_type_id)
  File "E:\New Jira_Jama\Jama_jira_script\Subprogress.py", line 309, in get_change_defects
    callback=data_reshape.getChangeDefects, endless=True)
  File "E:\New Jira_Jama\Jama_jira_script\api\api_common.py", line 179, in getResource
    return callback(rawdatas,rawmeta)
  File "E:\New Jira_Jama\Jama_jira_script\data_reshape.py", line 429, in getChangeDefects
    "priorityId":item["fields"]["priority"], "priority":"","upstream":"","jira":jira})
UnboundLocalError: local variable 'jira' referenced before assignment
